from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import AppSpec, AppStatus, Message, QueueDepth, VmRecord, WorkerStatus


@runtime_checkable
class Queue(Protocol):
    async def enqueue(self, dest: str, body: bytes, *, attributes: dict[str, str] | None = None) -> str: ...
    async def receive(self, source: str, *, max_messages: int, wait_seconds: int) -> list[Message]: ...
    async def ack(self, source: str, msg: Message) -> None: ...
    async def nack(self, source: str, msg: Message) -> None: ...
    async def extend_lease(self, source: str, msg: Message, seconds: int) -> None: ...
    async def depth(self, source: str) -> QueueDepth: ...


@runtime_checkable
class ObjectStore(Protocol):
    async def put(self, key: str, data: bytes, *, content_type: str | None = None) -> None: ...
    async def get(self, key: str) -> bytes: ...
    async def exists(self, key: str) -> bool: ...
    async def delete(self, key: str) -> None: ...
    async def signed_url(self, key: str, *, method: str = "GET", expires_s: int) -> str: ...
    async def list_keys(self, prefix: str) -> list[str]: ...


@runtime_checkable
class AppRegistry(Protocol):
    async def list_apps(self) -> list[AppSpec]: ...
    async def get_app(self, name: str) -> AppSpec | None: ...
    async def put_app(self, spec: AppSpec) -> None: ...
    async def delete_app(self, name: str) -> None: ...
    async def set_desired_state(self, name: str, state: str) -> None: ...
    async def write_status(self, name: str, status: AppStatus) -> None: ...
    async def get_status(self, name: str) -> AppStatus | None: ...


@runtime_checkable
class Cache(Protocol):
    async def get(self, key: str) -> bytes | None: ...
    async def set(self, key: str, value: bytes, *, ttl_s: int) -> None: ...
    async def delete(self, key: str) -> None: ...


@runtime_checkable
class ClusterInspector(Protocol):
    async def workers(self, app: AppSpec) -> list[WorkerStatus]: ...


@runtime_checkable
class ComputeProvider(Protocol):
    async def provision(self, app: AppSpec, *, region: str, pricing: str, count: int) -> list[VmRecord]: ...
    async def instance_states(self, app: str) -> list[VmRecord]: ...
    async def destroy(self, app: str, vm_ids: list[str]) -> None: ...


@runtime_checkable
class InferenceHandler(Protocol):
    async def load(self) -> None: ...
    async def predict(self, batch: list[object]) -> list[object]: ...
    async def health(self) -> bool: ...


@runtime_checkable
class InferenceObjects(Protocol):
    async def put_request(self, app: str, request_id: str, body: bytes) -> None: ...
    async def get_request(self, app: str, request_id: str) -> bytes: ...
    async def put_result(self, app: str, request_id: str, body: bytes) -> None: ...
    async def get_result(self, app: str, request_id: str) -> bytes: ...
    async def result_exists(self, app: str, request_id: str) -> bool: ...
